// Types for esolia-cicd-evidence Worker

export interface Env {
  readonly EVIDENCE_BUCKET: R2Bucket;
  readonly EVIDENCE_DB: D1Database;
  readonly GITHUB_OIDC_AUDIENCE: string;
  readonly GITHUB_ORG: string;
}

/** Decoded payload from a GitHub Actions OIDC JWT */
export interface GitHubOidcClaims {
  readonly sub: string; // e.g. "repo:esolia/periodic:ref:refs/heads/main"
  readonly aud: string;
  readonly iss: string; // "https://token.actions.githubusercontent.com"
  readonly repository: string; // "esolia/periodic"
  readonly repository_owner: string; // "esolia"
  readonly run_id: string;
  readonly sha: string;
  readonly ref: string;
  readonly actor: string;
  readonly workflow_ref: string;
  readonly exp: number;
  readonly iat: number;
  readonly nbf?: number;
}

/** Evidence manifest as generated by the workflow */
export interface EvidenceManifest {
  readonly schema_version: string;
  readonly report_type: 'cicd_evidence';
  readonly repository: string;
  readonly commit_sha: string;
  readonly ref: string;
  readonly run_id: string;
  readonly run_url: string;
  readonly actor: string;
  readonly policy_version: string;
  readonly decision: string;
  readonly generated_at: string;
  readonly artifacts: Record<string, ArtifactMeta>;
}

export interface ArtifactMeta {
  readonly sha256: string;
  readonly size_bytes: number;
}

/** Row shape in the D1 evidence_runs table */
export interface EvidenceRunRow {
  readonly id: string;
  readonly repository: string;
  readonly commit_sha: string;
  readonly ref: string;
  readonly run_id: string;
  readonly run_url: string;
  readonly actor: string;
  readonly policy_version: string;
  readonly decision: string;
  readonly manifest_hash: string;
  readonly r2_prefix: string;
  readonly created_at: string;
}
